### ISSUE TITLE
Parsing error: Found procedure call in MODULE

### ISSUE THREAD

**Issue by nncarlson** [cmacmackin/ford#88] opened 2015-09-05 21:21 UTC
I'm experimenting with ford for the first time and it chokes on this file
https://sourceforge.net/p/yajl-fort/code/ci/master/tree/src/yajl_fort.F90
giving the error message:
Reading file src/yajl_fort.F90
Warning: Error parsing src/yajl_fort.F90.
	Found procedure call in MODULE

I also stripped out all the pre-existing comments, so it was pure code, and that made no difference.  I wanted to attach the file here, but apparently github lacks that capability.

**Comment by cmacmackin** [comment] 2015-09-05 22:04
Could you try running FORD with the --debug flag and post the output 
here? I suspect I know what the issue is but that output should help me 
to nail it down.

On 05/09/15 06:21 PM, Neil Carlson wrote:
>
> I'm experimenting with ford for the first time and it chokes on this file
> https://sourceforge.net/p/yajl-fort/code/ci/master/tree/src/yajl_fort.F90
> giving the error message:
> Reading file src/yajl_fort.F90
> Warning: Error parsing src/yajl_fort.F90.
> Found procedure call in MODULE
>
> I also stripped out all the pre-existing comments, so it was pure 
> code, and that made no difference. I wanted to attach the file here, 
> but apparently github lacks that capability.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/88>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by nncarlson** [comment] 2015-09-06 02:43
$ ~/foo/bin/ford --debug yajl-fort.md 
Reading file src/yajl_fort.F90
Traceback (most recent call last):
  File "/home/nnc/foo/bin/ford", line 9, in <module>
    load_entry_point('FORD==4.2.3', 'console_scripts', 'ford')()
  File "/home/nnc/foo/lib/python2.7/site-packages/ford/__init__.py", line 282, in run
    main(proj_data,proj_docs,md)
  File "/home/nnc/foo/lib/python2.7/site-packages/ford/__init__.py", line 234, in main
    project = ford.fortran_project.Project(proj_data)
  File "/home/nnc/foo/lib/python2.7/site-packages/ford/fortran_project.py", line 84, in __init__
    self.files.append(ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings,fpp))
  File "/home/nnc/foo/lib/python2.7/site-packages/ford/sourceform.py", line 891, in __init__
    FortranContainer.__init__(self,source,"")
  File "/home/nnc/foo/lib/python2.7/site-packages/ford/sourceform.py", line 564, in __init__
    self.MODULE_RE.match(line),self))
  File "/home/nnc/foo/lib/python2.7/site-packages/ford/sourceform.py", line 656, in __init__
    raise Exception("Found procedure call in {}".format(type(self).__name__[7:].upper()))
Exception: Found procedure call in MODULE

**Comment by cmacmackin** [comment] 2015-09-06 02:44
Why did you close this?

On 05/09/15 11:43 PM, Neil Carlson wrote:
>
> Closed #88 <https://github.com/cmacmackin/ford/issues/88>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/88#event-402045263>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by nncarlson** [comment] 2015-09-06 02:52
Sorry, didn't mean to.  It wasn't clear to me what comment and close meant; now it does :)

**Comment by cmacmackin** [comment] 2015-09-09 01:40
The reason for this error was that I'd forgotten to support enumerations with FORD. It was then misinterpreting the `bind(c)` attribute on the enumeration as a function call. I've added support for enumerations now and will be creating a new release in the next few days.

**Comment by nncarlson** [comment] 2015-09-09 13:28
Great, I'll be watching for it and give it another try.

On 09/08/2015 07:40 PM, Chris MacMackin wrote:
> The reason for this error was that I'd forgotten to support enumerations
> with FORD. It was then misinterpreting the |bind(c)| attribute on the
> enumeration as a function call. I've added support for enumerations now
> and will be creating a new release in the next few days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmacmackin/ford/issues/88#issuecomment-138749575>.
>

-- 
Neil Carlson, Ph.D.
Telluride Project Leader
Computational Physics and Methods (CCS-2)
Los Alamos National Laboratory
PO Box 1663, MS D413 · Los Alamos, NM 87545
505.665.6386 · 505.665.4972 (fax)

**Comment by cmacmackin** [comment] 2015-09-20 21:31
I've released the corrected version of FORD to PyPI.

**Closed by cmacmackin** 2015-09-20 21:31 UTC
