### ISSUE TITLE
Unable to create FLAP API doc

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#116] opened 2016-03-23 15:17 UTC
Hi @cmacmackin 

with the new FORD version installed from PyPi I am not able to create the API doc of [FLAP](https://github.com/szaghi/FLAP).

I obtain this [error](https://travis-ci.org/szaghi/FLAP#L1204).

Can you help me to find what is wrong?

**Comment by cmacmackin** [comment] 2016-03-23 15:23
This was one of the problems fixed in #107. You can find a working version of the code in the `spoof` branch. I haven't authored a release yet because I was waiting to hear from @ollehellman whether a [problem](https://github.com/cmacmackin/ford/issues/45#issuecomment-198296446) they've had is still present in the branch with the fixes.

**Comment by szaghi** [comment] 2016-03-23 15:27
great!

I will test it soon... now!

Thank you!

**Comment by szaghi** [comment] 2016-03-23 15:33
@cmacmackin 

Chris, using the `spoof` branch seems to not work for my issue on FLAP:

```shell
stefano@zaghi(04:31 PM Wed Mar 23) on develop
~/fortran/FLAP 14 files, 128Kb
→ ~/python/ford/ford.py doc/main_page.md --debug
Reading file src/lib/flap_command_line_interface_t.F90
Reading file src/lib/flap_command_line_arguments_group_t.f90
Reading file src/lib/flap_utils_m.f90
Reading file src/lib/flap_command_line_argument_t.F90
Reading file src/lib/flap_object_t.f90
Reading file src/lib/flap.f90
Reading file src/third_party/IR_Precision/src/IR_Precision.f90
Reading file src/third_party/IR_Precision/src/Test_Driver.f90
Reading file src/tests/test_nested.f90
Reading file src/tests/test_choices_logical.f90
Reading file src/tests/test_string.f90
Reading file src/tests/test_basic.f90

Processing documentation comments...

Correlating information from different parts of your project...

Creating HTML documentation...
Traceback (most recent call last):
  File "/home/stefano/python/ford/ford/output.py", line 94, in __init__
    self.docs.append(ProcPage(data,project,item))
  File "/home/stefano/python/ford/ford/output.py", line 185, in __init__
    self.html = self.render(data,proj,obj)
  File "/home/stefano/python/ford/ford/output.py", line 325, in render
    return template.render(data,interface=obj,project=proj)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stefano/python/ford/ford/templates/genint_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/stefano/python/ford/ford/templates/base.html", line 99, in top-level template code
    {% block body %}
  File "/home/stefano/python/ford/ford/templates/genint_page.html", line 50, in block "body"
    {{ macros.proc_entry(proc.procedure) }}
  File "/home/stefano/python/ford/ford/templates/macros.html", line 633, in template
    <div class="panel-heading codesum"><span class="anchor" id="{{ proc.anchor }}"></span><h3>{{ proc_line(proc) }}</h3></div>
  File "/home/stefano/python/ford/ford/templates/macros.html", line 511, in template
    {% if proc.meta['deprecated'] and proc.meta['deprecated'].lower() == 'true' %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 389, in getitem
    return obj[argument]
UndefinedError: 'None' has no attribute 'meta'
Error encountered.
```

**Comment by cmacmackin** [comment] 2016-03-23 15:36
It did work to fix your previous problem--this is a different one. I'll 
have to take a look later to see what has gone wrong this time. And 
there I thought that all of the bugs had been caught months ago... :(

On 23/03/16 15:33, Stefano Zaghi wrote:
>
> @cmacmackin <https://github.com/cmacmackin>
>
> Chris, using the |spoof| branch seems to not work for my issue on FLAP:
>
> stefano@zaghi(04:31 PM Wed Mar 23) on develop
> ~/fortran/FLAP 14 files, 128Kb
> →~/python/ford/ford.py doc/main_page.md --debug
> Reading file src/lib/flap_command_line_interface_t.F90
> Reading file src/lib/flap_command_line_arguments_group_t.f90
> Reading file src/lib/flap_utils_m.f90
> Reading file src/lib/flap_command_line_argument_t.F90
> Reading file src/lib/flap_object_t.f90
> Reading file src/lib/flap.f90
> Reading file src/third_party/IR_Precision/src/IR_Precision.f90
> Reading file src/third_party/IR_Precision/src/Test_Driver.f90
> Reading file src/tests/test_nested.f90
> Reading file src/tests/test_choices_logical.f90
> Reading file src/tests/test_string.f90
> Reading file src/tests/test_basic.f90
>
> Processing documentation comments...
>
> Correlating information from different parts of your project...
>
> Creating HTML documentation...
> Traceback (most recent call last):
>    File"/home/stefano/python/ford/ford/output.py", line 94,in  __init__
>      self.docs.append(ProcPage(data,project,item))
>    File"/home/stefano/python/ford/ford/output.py", line 185,in  __init__
>      self.html = self.render(data,proj,obj)
>    File"/home/stefano/python/ford/ford/output.py", line 325,in  render
>      return  template.render(data,interface=obj,project=proj)
>    File"/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989,in  render
>      return  self.environment.handle_exception(exc_info, True)
>    File"/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754,in  handle_exception
>      reraise(exc_type, exc_value, tb)
>    File"/home/stefano/python/ford/ford/templates/genint_page.html", line 1,in  top-level template code
>      {% extends"base.html"  %}
>    File"/home/stefano/python/ford/ford/templates/base.html", line 99,in  top-level template code
>      {% block body %}
>    File"/home/stefano/python/ford/ford/templates/genint_page.html", line 50,in  block"body"
>      {{ macros.proc_entry(proc.procedure) }}
>    File"/home/stefano/python/ford/ford/templates/macros.html", line 633,in  template
>      <div class="panel-heading codesum"><span class="anchor"  id="{{ proc.anchor }}"></span><h3>{{ proc_line(proc) }}</h3></div>
>    File"/home/stefano/python/ford/ford/templates/macros.html", line 511,in  template
>      {%if  proc.meta['deprecated'] andproc.meta['deprecated'].lower() =='true'  %}
>    File"/usr/lib/python2.7/site-packages/jinja2/environment.py", line 389,in  getitem
>      return  obj[argument]
> UndefinedError:'None'  has no attribute'meta'
> Error encountered.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/116#issuecomment-200396535>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by cmacmackin** [comment] 2016-03-27 19:43
I can't seem to reproduce this error. Could you try running again using the current `master` branch on GitHub?

**Comment by szaghi** [comment] 2016-03-29 07:18
@cmacmackin 
No way to work for me...

### Ford from PyPi  (v4.5.3)

```shell
→ sudo pip install --upgrade ford
[sudo] password for stefano: 
Collecting ford
  Downloading FORD-4.5.3.tar.gz (610kB)
    100% |████████████████████████████████| 614kB 1.5MB/s 
Requirement already up-to-date: markdown in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: markdown-include>=0.5.1 in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: toposort in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: jinja2>=2.1 in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: pygments in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: beautifulsoup4 in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: graphviz in /usr/lib/python2.7/site-packages (from ford)
Requirement already up-to-date: MarkupSafe in /usr/lib/python2.7/site-packages (from jinja2>=2.1->ford)
Installing collected packages: ford
  Found existing installation: FORD 4.5.2
    Uninstalling FORD-4.5.2:
      Successfully uninstalled FORD-4.5.2
  Running setup.py install for ford ... done
Successfully installed ford-4.5.3
```

```shell
stefano@zaghi(09:06 AM Tue Mar 29) on master
~/fortran/FLAP 13 files, 120Kb
→ FoBiS.py rule -ex makedoc
Executing rule "makedoc"
   Command => rm -rf doc/html/*
   Command => ford doc/main_page.md --debug
   Command => cp -r doc/html/publish/* doc/html/
Reading file src/lib/flap_command_line_interface_t.F90
Reading file src/lib/flap_command_line_arguments_group_t.f90
Reading file src/lib/flap_utils_m.f90
Reading file src/lib/flap_command_line_argument_t.F90
Reading file src/lib/flap_object_t.f90
Reading file src/lib/flap.f90
Reading file src/third_party/PENF/src/lib/penf.F90
Traceback (most recent call last):
  File "/usr/bin/ford", line 9, in <module>
    load_entry_point('FORD==4.5.3', 'console_scripts', 'ford')()
  File "/usr/lib/python2.7/site-packages/ford/__init__.py", line 313, in run
    main(proj_data,proj_docs,md)
  File "/usr/lib/python2.7/site-packages/ford/__init__.py", line 265, in main
    project = ford.fortran_project.Project(proj_data)
  File "/usr/lib/python2.7/site-packages/ford/fortran_project.py", line 91, in __init__
    self.files.append(ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings,fpp))
  File "/usr/lib/python2.7/site-packages/ford/sourceform.py", line 928, in __init__
    FortranContainer.__init__(self,source,"")
  File "/usr/lib/python2.7/site-packages/ford/sourceform.py", line 588, in __init__
    self.MODULE_RE.match(line),self))
  File "/usr/lib/python2.7/site-packages/ford/sourceform.py", line 630, in __init__
    self,permission)
  File "/usr/lib/python2.7/site-packages/ford/sourceform.py", line 569, in __init__
    self._cleanup()
  File "/usr/lib/python2.7/site-packages/ford/sourceform.py", line 1513, in _cleanup
    raise Exception("Generic interface block found with no contents: {}".format(self.name))
Exception: Generic interface block found with no contents: bit_size
```

### Ford from GitHub master branch

```shell
stefano@zaghi(09:08 AM Tue Mar 29) on master
~/fortran/FLAP 13 files, 120Kb
→ sudo pip uninstall ford          
Uninstalling FORD-4.5.3:
...
Proceed (y/n)? y
  Successfully uninstalled FORD-4.5.3
```

```shell
stefano@zaghi(09:09 AM Tue Mar 29)
~/python 26 files, 112Kb
→ git clone https://github.com/cmacmackin/ford
Cloning into 'ford'...
remote: Counting objects: 1247, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1247 (delta 5), reused 0 (delta 0), pack-reused 1232
Receiving objects: 100% (1247/1247), 6.25 MiB | 5.39 MiB/s, done.
Resolving deltas: 100% (920/920), done.
Checking connectivity... done.
→ ~/python/ford/ford.py doc/main_page.md --debug
Reading file src/lib/flap_command_line_interface_t.F90
Reading file src/lib/flap_command_line_arguments_group_t.f90
Reading file src/lib/flap_utils_m.f90
Reading file src/lib/flap_command_line_argument_t.F90
Reading file src/lib/flap_object_t.f90
Reading file src/lib/flap.f90
Reading file src/third_party/PENF/src/lib/penf.F90
Traceback (most recent call last):
  File "/home/stefano/python/ford/ford.py", line 7, in <module>
    run()
  File "/home/stefano/python/ford/ford/__init__.py", line 313, in run
    main(proj_data,proj_docs,md)
  File "/home/stefano/python/ford/ford/__init__.py", line 265, in main
    project = ford.fortran_project.Project(proj_data)
  File "/home/stefano/python/ford/ford/fortran_project.py", line 91, in __init__
    self.files.append(ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings,fpp))
  File "/home/stefano/python/ford/ford/sourceform.py", line 928, in __init__
    FortranContainer.__init__(self,source,"")
  File "/home/stefano/python/ford/ford/sourceform.py", line 588, in __init__
    self.MODULE_RE.match(line),self))
  File "/home/stefano/python/ford/ford/sourceform.py", line 630, in __init__
    self,permission)
  File "/home/stefano/python/ford/ford/sourceform.py", line 569, in __init__
    self._cleanup()
  File "/home/stefano/python/ford/ford/sourceform.py", line 1513, in _cleanup
    raise Exception("Generic interface block found with no contents: {}".format(self.name))
Exception: Generic interface block found with no contents: bit_size
```

### The problem

The problem seems to be into PENF (the old IR_Precision): I have refactored this module, thus now I need an empty generic interface for the overloaded [bit_size](https://github.com/szaghi/PENF/blob/83855392afcb85147b48a68a1a83d2160f37d152/src/lib/penf.F90#L1428) function, this is a workaround for a possible gfortran bug.

**Comment by cmacmackin** [comment] 2016-03-29 08:28
Ah, I had forgotten to download all of the submodules when I cloned FLAP. I wasn't aware that empty generic interfaces were legal and thus had FORD raise an error if it encountered one. I've made another new release with this fixed.

**Closed by cmacmackin** 2016-03-29 08:28 UTC

**Comment by szaghi** [comment] 2016-03-29 08:41
Now works smoothly,

great Chris!

Anyhow, I am not sure my empty-generic-interface-workaround is legal... it just make gfortran working...

Maybe @zbeekman can illuminate us?

See you soon (with FIAT).

**Comment by zbeekman** [comment] 2016-04-03 23:55
@szaghi: Ah, I see. Can you show me the error message GFortran is giving you without [that work around](https://github.com/szaghi/PENF/blob/83855392afcb85147b48a68a1a83d2160f37d152/src/lib/penf.F90#L1428)?

Off the top of my head I don't remember for sure whether or not it is legal to overload intrinsic functions, but I think it should be.

**Comment by cmacmackin** [comment] 2016-04-04 08:04
It is definitely legal to overload intrinsic functions. I'm just not sure whether you're allowed to have an interface block with no contents.

**Comment by zbeekman** [comment] 2016-04-04 18:02
Yes that is a good question too... it seems like this is required to get around a GFortran bug... @szaghi I think you should file a bug report with GCC, but you may need to make a simpler/smaller reproducer program.

**Comment by szaghi** [comment] 2016-04-04 20:20
@zbeekman @cmacmackin sorry guys, these are busy days... I hope to come back soon...
