### ISSUE TITLE
Header hides source listing, especially target anchor

### ISSUE THREAD

**Issue by p-vitt** [cmacmackin/ford#132] opened 2016-04-25 09:47 UTC
When you access a source file listing via line anchor (url.to.doc/project/sourcefile/file.f90.html#ln-123), the first few lines are hidden by the header bar. Unfortunately, the targeted line is shown at the very top of the page, so you don't see the actual target of the link, which could confuse people. 
Once you figured out that you have to scroll up a bit to see the real target, it's not that big of a problem. But until then it is quite confusing and also a little annoying.

As I'm not an HTML expert, I don't have an easy fix for that.

**Comment by p-vitt** [comment] 2016-04-25 10:04
It seems to be a known problem when using bootstrap's navbar-fixed-top class: [Bootstrap hides portion of container below navbar](http://stackoverflow.com/questions/14735274/bootstrap-css-hides-portion-of-container-below-navbar-navbar-fixed-top#comment49382109_14735425)

**Comment by p-vitt** [comment] 2016-04-25 10:12
And it seems to be inherent when using the [`position:fixed` attribute](http://stackoverflow.com/a/14735451/128886).

**Comment by cmacmackin** [comment] 2016-04-25 11:04
This was also a problem for other links within pages and there was a way I fixed that with a bit of CSS. I may be able to fix it in this case too.

**Comment by cmacmackin** [comment] 2016-05-07 12:03
Fixed this with some CSS. Will be in the next release.

**Closed by cmacmackin** 2016-05-07 12:03 UTC

**Comment by Schildkroete23** [comment] 2016-09-19 22:03
The line anchors in source listings are hidden by menu again. I've seen that you changed the local.css file for fixing this. It seems to me that currently this file has no effect to the output (when I remove this file the styling is the same), but I'm not good in html and css at all...

**Comment by cmacmackin** [comment] 2016-09-24 10:06
I can't reproduce this. Can you tell me which version of FORD you are using?

**Comment by Schildkroete23** [comment] 2016-09-25 20:51
FORD 5.0.6. The source listings are not hidden by the menu again. This works fine. I meant the headers when  accessed via line anchor within pages (e.g. via a TOC link). I don't no why I wrote that the source listings are hidden again. I'm sorry for that!
